version: '3.8'
services:
  server:
    build: ./server
    container_name: loanyst-loan-api
    ports:
      - '8001:3001'
    environment:
      - ENABLE_ACCOUNTING_SOFTWARE_SIMULATION=true
      - ENABLE_DECISION_ENGINE_SIMULATION=true
    tty: true
  client:
    build: ./client
    container_name: loanyst-loan-app
    ports:
      - '8000:3000'
    environment:
      - REACT_APP_SERVER_HOST=localhost
      - REACT_APP_SERVER_PORT=8001
    stdin_open: true
    tty: true
